// Mocks generated by Mockito 5.4.6 from annotations
// in projectunity/test/unit_test/space/edit_space_test/edit_space_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i12;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_storage/firebase_storage.dart' as _i5;
import 'package:image_picker/image_picker.dart' as _i13;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:projectunity/data/model/account/account.dart' as _i11;
import 'package:projectunity/data/model/employee/employee.dart' as _i3;
import 'package:projectunity/data/model/space/space.dart' as _i9;
import 'package:projectunity/data/provider/user_state.dart' as _i10;
import 'package:projectunity/data/services/space_service.dart' as _i6;
import 'package:projectunity/data/services/storage_service.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmployee_1 extends _i1.SmartFake implements _i3.Employee {
  _FakeEmployee_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLostDataResponse_2 extends _i1.SmartFake
    implements _i4.LostDataResponse {
  _FakeLostDataResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseStorage_3 extends _i1.SmartFake
    implements _i5.FirebaseStorage {
  _FakeFirebaseStorage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpaceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpaceService extends _i1.Mock implements _i6.SpaceService {
  MockSpaceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get fireStore =>
      (super.noSuchMethod(
            Invocation.getter(#fireStore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#fireStore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  String get generateNewSpaceId =>
      (super.noSuchMethod(
            Invocation.getter(#generateNewSpaceId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#generateNewSpaceId),
            ),
          )
          as String);

  @override
  set fireStore(_i2.FirebaseFirestore? value) => super.noSuchMethod(
    Invocation.setter(#fireStore, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i9.Space?> getSpace(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getSpace, [spaceId]),
            returnValue: _i8.Future<_i9.Space?>.value(),
          )
          as _i8.Future<_i9.Space?>);

  @override
  _i8.Future<void> createSpace({required _i9.Space? space}) =>
      (super.noSuchMethod(
            Invocation.method(#createSpace, [], {#space: space}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSpace(_i9.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpace, [space]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteSpace({
    required String? spaceId,
    required List<String>? owners,
    required String? uid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSpace, [], {
              #spaceId: spaceId,
              #owners: owners,
              #uid: uid,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getPaidLeaves({required String? spaceId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPaidLeaves, [], {#spaceId: spaceId}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);
}

/// A class which mocks [UserStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserStateNotifier extends _i1.Mock implements _i10.UserStateNotifier {
  MockUserStateNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.UserState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i10.UserState.authenticated,
          )
          as _i10.UserState);

  @override
  String get employeeId =>
      (super.noSuchMethod(
            Invocation.getter(#employeeId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#employeeId),
            ),
          )
          as String);

  @override
  _i3.Employee get employee =>
      (super.noSuchMethod(
            Invocation.getter(#employee),
            returnValue: _FakeEmployee_1(this, Invocation.getter(#employee)),
          )
          as _i3.Employee);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  bool get isEmployee =>
      (super.noSuchMethod(Invocation.getter(#isEmployee), returnValue: false)
          as bool);

  @override
  bool get isHR =>
      (super.noSuchMethod(Invocation.getter(#isHR), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void getUserStatus() => super.noSuchMethod(
    Invocation.method(#getUserStatus, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setUser(_i11.Account? user) =>
      (super.noSuchMethod(
            Invocation.method(#setUser, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setEmployeeWithSpace({
    required _i9.Space? space,
    required _i3.Employee? spaceUser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setEmployeeWithSpace, [], {
              #space: space,
              #spaceUser: spaceUser,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setEmployee({required _i3.Employee? member}) =>
      (super.noSuchMethod(
            Invocation.method(#setEmployee, [], {#member: member}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setSpace({required _i9.Space? space}) =>
      (super.noSuchMethod(
            Invocation.method(#setSpace, [], {#space: space}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSpace(_i9.Space? space) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpace, [space]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeEmployeeWithSpace() =>
      (super.noSuchMethod(
            Invocation.method(#removeEmployeeWithSpace, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeAll() =>
      (super.noSuchMethod(
            Invocation.method(#removeAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i13.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.XFile?> pickImage({
    required _i4.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i4.CameraDevice? preferredCameraDevice = _i4.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<_i4.XFile?>.value(),
          )
          as _i8.Future<_i4.XFile?>);

  @override
  _i8.Future<List<_i4.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<List<_i4.XFile>>.value(<_i4.XFile>[]),
          )
          as _i8.Future<List<_i4.XFile>>);

  @override
  _i8.Future<_i4.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<_i4.XFile?>.value(),
          )
          as _i8.Future<_i4.XFile?>);

  @override
  _i8.Future<List<_i4.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<List<_i4.XFile>>.value(<_i4.XFile>[]),
          )
          as _i8.Future<List<_i4.XFile>>);

  @override
  _i8.Future<_i4.XFile?> pickVideo({
    required _i4.ImageSource? source,
    _i4.CameraDevice? preferredCameraDevice = _i4.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i8.Future<_i4.XFile?>.value(),
          )
          as _i8.Future<_i4.XFile?>);

  @override
  _i8.Future<_i4.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i8.Future<_i4.LostDataResponse>.value(
              _FakeLostDataResponse_2(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i8.Future<_i4.LostDataResponse>);

  @override
  bool supportsImageSource(_i4.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i14.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseStorage get firebaseStorage =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseStorage),
            returnValue: _FakeFirebaseStorage_3(
              this,
              Invocation.getter(#firebaseStorage),
            ),
          )
          as _i5.FirebaseStorage);

  @override
  _i8.Future<String> uploadProfilePic({
    required String? path,
    required String? imagePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePic, [], {
              #path: path,
              #imagePath: imagePath,
            }),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePic, [], {
                  #path: path,
                  #imagePath: imagePath,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deleteProfileImage(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileImage, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteStorageFolder(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStorageFolder, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
